Refactor

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -6,9 +6,7 @@ set -e
 mkdir -p "$1" "$2"
 build=$(cd "$1/" && pwd)
 cache=$(cd "$2/" && pwd)
-ver=go1
-file=go.$ver.linux-amd64.tar.gz
-url=http://go.googlecode.com/files/$file
+ver=go1.0.2
 buildpack=$(dirname $(dirname $0))
 
 # Python
@@ -21,10 +19,9 @@ virtualenv() {
     python "$buildpack/vendor/virtualenv-1.7/virtualenv.py" "$@"
 }
 
-if ! test -f $build/.godir
+if ! test -f $build/.godir || test -z "$(cat $build/.godir)"
 then
-    echo >&2 '-----> ERROR: Please create .godir'
-    echo >&2 '-----> See https://gist.github.com/4984b5d9fe9244776197 for instructions'
+    echo >&2 '-----> ERROR: Please create .godir containing the package name of your project (e.g. github.com/org/goprj)'
     exit 1
 fi
 
@@ -50,44 +47,35 @@ echo "-----> Checking for Mercurial and Bazaar"
 
     pip install --use-mirrors mercurial
     pip install --use-mirrors bzr
-) 2>&1 | sed -u 's/^/       /'
-
-. $venv/bin/activate
+) 2>&1 | sed 's/^/       /'
 
 echo "-----> Using Go $ver"
-
 (
     set -e
 
-    # Already cached?
-    test -d $cache/go-source/go && exit
+    echo "Installing Go $ver -- this only happens once, please be patient"
 
-    rm -rf $cache/* # be sure not to build up cruft
-    mkdir -p $cache/go-source
-    cd $cache/go-source
-    echo "-----> Fetching latest Go source"
-    hg clone $url
-    ./go/src/all.bash
+    test ! -e $cache/go || exit 0
+
+    cd $cache
+    hg clone https://code.google.com/p/go
+    cd go/src
+    GOBIN=$cache/go/bin ./all.bash
 )
 
-GOROOT=$cache/go-source/go export GOROOT
-GOPATH=$build/.heroku/g export GOPATH
-PATH=$GOROOT/bin:$PATH
-
-name=$(cat $build/.godir)
-p=$GOPATH/src/$name
-mkdir -p $p
-cp -R $build/* $p
-
-unset GIT_DIR # unset git dir or it will mess with goinstall
 echo "-----> Running go get and go install"
-cd $p
-for f in $(find . -type f -name '*.go')
-do
-    go get $(dirname $f)
-    go install $(dirname $f)
-done
+set -x
+name=$(cat $build/.godir)
+gopath=${cache}/.gopath
+pkg_gopath=${gopath}/src/${name}
 
-mkdir -p $build/bin
-mv $GOPATH/bin/* $build/bin
-rm -rf $build/.heroku
+unset GIT_DIR
+
+mkdir -p $(dirname ${pkg_gopath})
+ln -sfn ${build} ${pkg_gopath}
+cd ${pkg_gopath}
+mkdir -p bin
+
+unset GOROOT
+PATH=$cache/go/bin:${PATH} GOPATH=${gopath} go get -v -d
+PATH=$cache/go/bin:${PATH} GOPATH=${gopath} GOBIN=${build}/bin go install -v ${name}
