Revert changes and use a snapshot archive instead

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -6,7 +6,9 @@ set -e
 mkdir -p "$1" "$2"
 build=$(cd "$1/" && pwd)
 cache=$(cd "$2/" && pwd)
-ver=go1.0.2
+ver=unstable
+file=go.$ver.tar.gz
+url=http://dl.dropbox.com/u/211105/$file
 buildpack=$(dirname $(dirname $0))
 
 # Python
@@ -19,9 +21,10 @@ virtualenv() {
     python "$buildpack/vendor/virtualenv-1.7/virtualenv.py" "$@"
 }
 
-if ! test -f $build/.godir || test -z "$(cat $build/.godir)"
+if ! test -f $build/.godir
 then
-    echo >&2 '-----> ERROR: Please create .godir containing the package name of your project (e.g. github.com/org/goprj)'
+    echo >&2 '-----> ERROR: Please create .godir'
+    echo >&2 '-----> See https://gist.github.com/4984b5d9fe9244776197 for instructions'
     exit 1
 fi
 
@@ -30,6 +33,29 @@ then
     echo >&2 '-----> ERROR: File bin exists and is not a directory.'
     exit 1
 fi
+
+echo "-----> Using Go $ver"
+
+(
+    set -e
+
+    # Already cached?
+    test -d $cache/go-$ver/go && exit
+
+    rm -rf $cache/* # be sure not to build up cruft
+    mkdir -p $cache/go-$ver
+    cd $cache/go-$ver
+    echo "-----> Fetching Go $ver"
+    curl -sO $url
+    tar zxf $file
+    rm -f $file
+
+    ./go/src/all.bash
+)
+
+GOROOT=$cache/go-$ver/go export GOROOT
+GOPATH=$build/.heroku/g export GOPATH
+PATH=$GOROOT/bin:$PATH
 
 echo "-----> Checking for Mercurial and Bazaar"
 (
@@ -47,40 +73,22 @@ echo "-----> Checking for Mercurial and Bazaar"
 
     pip install --use-mirrors mercurial
     pip install --use-mirrors bzr
-) 2>&1 | sed 's/^/       /'
+) 2>&1 | sed -u 's/^/       /'
 
-echo "-----> Using Go $ver"
-(
-    set -e
-
-    echo "Installing Go $ver -- this only happens once, please be patient"
-
-    test ! -e $cache/go || exit 0
-
-    cd $cache
-    hg clone https://code.google.com/p/go
-    cd go/src
-    GOBIN=$cache/go/bin ./all.bash
-)
-
-echo "-----> Running go get and go install"
-set -x
 name=$(cat $build/.godir)
-gopath=${cache}/.gopath
-pkg_gopath=${gopath}/src/${name}
+p=$GOPATH/src/$name
+mkdir -p $p
+cp -R $build/* $p
 
-unset GIT_DIR
-
-mkdir -p $(dirname ${pkg_gopath})
-ln -sfn ${build} ${pkg_gopath}
-cd ${pkg_gopath}
-mkdir -p bin
-
-unset GOROOT
-
+unset GIT_DIR # unset git dir or it will mess with goinstall
+echo "-----> Running go get and go install"
+cd $p
 for f in $(find . -type f -name '*.go')
 do
-    PATH=$cache/go/bin:${PATH} GOPATH=${gopath} go get $(dirname $f)
-    PATH=$cache/go/bin:${PATH} GOPATH=${gopath} GOBIN=${build}/bin go install $(dirname $f)
+    go get $(dirname $f)
+    go install $(dirname $f)
 done
 
+mkdir -p $build/bin
+mv $GOPATH/bin/* $build/bin
+rm -rf $build/.heroku
